"""Pydantic schemas for inter-agent communication."""
from pydantic import BaseModel, Field
from typing import Optional
from enum import Enum


class AgentStepStatus(str, Enum):
    PENDING = "Pending"
    RUNNING = "Running"
    COMPLETED = "Completed"
    FAILED = "Failed"


class PlanStep(BaseModel):
    """A single step in the workflow plan."""
    step_number: int = Field(..., description="Order of execution")
    agent: str = Field(..., description="Agent name to execute this step")
    task: str = Field(..., description="Task description for the agent")
    required_tools: list[str] = Field(
        default_factory=list, description="Tools the agent needs"
    )
    depends_on: list[int] = Field(
        default_factory=list, description="Step numbers this depends on"
    )


class WorkflowPlanOutput(BaseModel):
    """Structured plan generated by the Coordinator Agent via Gemini."""
    objective: str = Field(..., description="The overall workflow objective")
    steps: list[PlanStep] = Field(..., description="Ordered list of execution steps")
    reasoning: str = Field(..., description="Why this plan was chosen")


class CandidateAnalysisInput(BaseModel):
    """Input to the Candidate Analysis Agent."""
    application_id: str
    job_id: str
    workflow_id: str


class SkillMatchResult(BaseModel):
    """Result of matching a single skill."""
    skill_name: str
    is_mandatory: bool
    is_matched: bool
    candidate_proficiency: Optional[str] = None
    candidate_years: int = 0
    weight: int = 0


class CandidateAnalysisOutput(BaseModel):
    """Structured output from the Candidate Analysis Agent."""
    application_id: str
    job_id: str
    candidate_name: str = ""
    mandatory_skill_matches: list[SkillMatchResult] = Field(default_factory=list)
    preferred_skill_matches: list[SkillMatchResult] = Field(default_factory=list)
    total_experience_years: float = 0.0
    minimum_required_years: int = 0
    meets_experience_requirement: bool = False
    education_summary: str = ""
    qualitative_analysis: str = ""
    evidence_summary: str = ""


class ValidationInput(BaseModel):
    """Input to the Validation Agent."""
    workflow_id: str
    application_id: str
    job_id: str
    candidate_analysis: Optional[CandidateAnalysisOutput] = None
    score_result: Optional[dict] = None


class ValidationOutput(BaseModel):
    """Output from the Validation Agent."""
    is_valid: bool
    risk_level: str = "Low"  # Low, Medium, High
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    checks_performed: list[str] = Field(default_factory=list)


class InterviewSchedulingInput(BaseModel):
    """Input to the Interview Agent."""
    workflow_id: str
    application_id: str
    candidate_profile_id: str
    interviewer_ids: list[str] = Field(default_factory=list)
    preferred_date_range_start: Optional[str] = None
    preferred_date_range_end: Optional[str] = None


class ProposedSlot(BaseModel):
    """A proposed interview time slot."""
    start_time: str
    end_time: str
    available_interviewers: list[str] = Field(default_factory=list)
    all_available: bool = True


class InterviewSchedulingOutput(BaseModel):
    """Output from the Interview Agent."""
    application_id: str
    proposed_slots: list[ProposedSlot] = Field(default_factory=list)
    recommendation: str = ""
    notes: str = ""


class WorkflowResult(BaseModel):
    """Final compiled result from the Coordinator Agent."""
    workflow_id: str
    application_id: str
    job_id: str
    candidate_analysis: Optional[CandidateAnalysisOutput] = None
    score: Optional[dict] = None
    validation: Optional[ValidationOutput] = None
    interview_proposal: Optional[InterviewSchedulingOutput] = None
    overall_recommendation: str = ""
    requires_approval: bool = True
    summary: str = ""
