env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://host.docker.internal:5178/
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: http://host.docker.internal:5178/
  type: spider
- parameters:
    maxDuration: 3
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: web-report.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: web-report.md
    reportTitle: ZAP Scanning Report
    template: traditional-md
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: web-report.json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
